---
- name: Backup docker minecraft.
  import_playbook: minecraft/minecraft-docker-backup.yml
  tags: ['minecraft']

- name: Backup macbook.
  import_playbook: macbook/macbook-backup.yml
  tags: ['macbook']

- name: Backup home assistant.
  import_playbook: home-assistant/home-assistant-backup.yml
  tags: ['home-assistant']

# Not using minecraft kubernetes yet
# - name: Backup minecraft.
#   import_playbook: minecraft/minecraft-backup.yml
#   tags: ['minecraft']